name: Docker

on: [push, pull_request]

jobs:

  create-image:
    name: create docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Docker image
        with:
          image: cgellerac/carla-scenario-runner
          tags: latest
          dockerfile: docker/docker-compose.yml
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
