name: Docker

on: [push, pull_request]

jobs:
  
  clean-up:
    name: Clean up
    runs-on: self-hosted
    steps:

      - name: Clean up
        run: rm -rf *
        
  create-image:
    name: Create docker image
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v4
        name: Checkout repository
        with: 
          path: scenario-runner
          submodules: true
          
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: robinraju/release-downloader@v1.8
        name: Download PythonAPI
        with:
          repository: carla-compose/carla-simulator
          latest: true
          fileName: PythonAPI.tar.gz
          extract: true          
          out-file-path: artifacts
        
      - name: Remove PythonAPI.tar.gz
        run: rm artifacts/PythonAPI.tar.gz
        
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: scenario-runner/docker/Dockerfile
          tags: cgellerac/carla-scenario-runner
          no-cache: true
          context: .

      - uses: ncipollo/release-action@v1
        name: Create Release
        if: startsWith(github.ref, 'refs/tags')
        with:
          allowUpdates: true
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
